"""
Django settings for doctor project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = True
SECRET_KEY = "this-is-a-secret-key"
ALLOWED_HOSTS = ["cl-doctor", "0.0.0.0", "localhost"]
INSTALLED_APPS = []
ROOT_URLCONF = "doctor.urls"
WSGI_APPLICATION = "doctor.wsgi.application"
