"""
Django settings for doctor project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import environ
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

env = environ.FileAwareEnv()

BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = env.bool("DEBUG", default=False)
SECRET_KEY = "this-is-a-not-so-secret-key"
ALLOWED_HOSTS = ["doctor", "0.0.0.0", "localhost"]
INSTALLED_APPS = []
ROOT_URLCONF = "doctor.urls"
ASGI_APPLICATION = "doctor.asgi.application"


# Host allowlist for endpoints that fetch or upload caller-supplied
# URLs (currently the bitonal endpoint). Comma-separated fnmatch
# patterns; when set, URLs must be https and match one of them. The
# default admits any AWS host (presigned S3 URLs) while blocking
# SSRF at cluster-internal services; deployments can pin it down to
# exact bucket hostnames. Set it empty to disable the check, which
# is what local dev and the test suite need (see .env.example).
DOCTOR_EGRESS_ALLOWED_HOSTS = [
    host.strip()
    for host in env(
        "DOCTOR_EGRESS_ALLOWED_HOSTS", default="*.amazonaws.com"
    ).split(",")
    if host.strip()
]

SENTRY_DSN = env("SENTRY_DSN", default="")
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
        ],
        ignore_errors=[KeyboardInterrupt],
    )

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "()": "doctor.lib.utils.UTCFormatter",
            "format": "%(asctime)s.%(msecs)03dZ %(levelname)s %(name)s: %(message)s",
            "datefmt": "%Y-%m-%dT%H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "doctor": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
