"""
Django settings for doctor project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import environ
import sentry_sdk

from pathlib import Path
from sentry_sdk.integrations.django import DjangoIntegration

env = environ.FileAwareEnv()

BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = env.bool("DEBUG", default=False)
SECRET_KEY = "this-is-a-not-so-secret-key"
ALLOWED_HOSTS = ["doctor", "0.0.0.0", "localhost"]
INSTALLED_APPS = []
ROOT_URLCONF = "doctor.urls"
WSGI_APPLICATION = "doctor.wsgi.application"


SENTRY_DSN = env("SENTRY_DSN", default="")
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
        ],
        ignore_errors=[KeyboardInterrupt],
    )
