"""
Django settings for bte project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = True
ALLOWED_HOSTS = ["bte", "0.0.0.0", "localhost"]
INSTALLED_APPS = []
ROOT_URLCONF = "bte.urls"
WSGI_APPLICATION = "bte.wsgi.application"
