name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Black Code Formatter
        uses: psf/black@stable
